// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Infrastructure.EF;

#nullable disable

namespace ToDo.Infrastructure.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20230226123637_SeedData3")]
    partial class SeedData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDo.Core.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToDoListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ToDoItemId");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = new Guid("ba3282cb-3ddc-4bac-933e-8c7010274fed"),
                            CreatedDate = new DateTime(2023, 2, 26, 13, 36, 36, 933, DateTimeKind.Local).AddTicks(178),
                            Description = "first item",
                            DueDate = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item1",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("5fb234a3-ac32-42ed-a85c-8c93f628d721")
                        },
                        new
                        {
                            ToDoItemId = new Guid("bae11e95-dd2e-4039-822a-fb4ab9947838"),
                            CreatedDate = new DateTime(2023, 2, 26, 13, 36, 36, 933, DateTimeKind.Local).AddTicks(199),
                            Description = "second item",
                            DueDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item2",
                            Notes = "low priority",
                            Status = 0,
                            ToDoListId = new Guid("5fb234a3-ac32-42ed-a85c-8c93f628d721")
                        },
                        new
                        {
                            ToDoItemId = new Guid("6e5bb5b6-80a7-4f09-9e7d-62d20dcea7e4"),
                            CreatedDate = new DateTime(2023, 2, 26, 13, 36, 36, 933, DateTimeKind.Local).AddTicks(205),
                            Description = "first item",
                            DueDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item1",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("40ce6fbf-c8de-4542-8d9f-0d8b079ec8e0")
                        },
                        new
                        {
                            ToDoItemId = new Guid("3f05dc62-3467-4486-8105-6952a1e142e0"),
                            CreatedDate = new DateTime(2023, 2, 26, 13, 36, 36, 933, DateTimeKind.Local).AddTicks(210),
                            Description = "first item",
                            DueDate = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "First user item",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("265217c0-acff-4e87-b3cb-e4c3800efdc0")
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.Property<Guid>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HiddenFinishedItems")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.HasKey("ToDoListId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ToDoListId = new Guid("5fb234a3-ac32-42ed-a85c-8c93f628d721"),
                            HiddenFinishedItems = false,
                            Name = "Admin list1",
                            UserId = new Guid("d6480d35-0c2a-4a7b-a894-3c1c20997249"),
                            Visibility = true
                        },
                        new
                        {
                            ToDoListId = new Guid("40ce6fbf-c8de-4542-8d9f-0d8b079ec8e0"),
                            HiddenFinishedItems = false,
                            Name = "Admin list2",
                            UserId = new Guid("d6480d35-0c2a-4a7b-a894-3c1c20997249"),
                            Visibility = true
                        },
                        new
                        {
                            ToDoListId = new Guid("265217c0-acff-4e87-b3cb-e4c3800efdc0"),
                            HiddenFinishedItems = false,
                            Name = "test list1",
                            UserId = new Guid("ccfb5104-4606-464d-8d28-c8c6e3a0a10e"),
                            Visibility = true
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d6480d35-0c2a-4a7b-a894-3c1c20997249"),
                            Password = "AQAAAAEAACcQAAAAELb8RYqJdzn7PLBd+LYUfJn41mOC14H7ygPPLYW0R5eQxEoMVo3ztNlSNSaZ+Kcl7w==",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("ccfb5104-4606-464d-8d28-c8c6e3a0a10e"),
                            Password = "AQAAAAEAACcQAAAAEIPSI/aIdKAHjhvblFJggL1gRyOx5vHTHgGtovz03EPuOfgZ8Tm7o4vWgXk9YWyHKw==",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoItem", b =>
                {
                    b.HasOne("ToDo.Core.Entities.ToDoList", "ToDoList")
                        .WithMany("Items")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.HasOne("ToDo.Core.Entities.User", "User")
                        .WithMany("ToDoLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ToDo.Core.Entities.User", b =>
                {
                    b.Navigation("ToDoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
