// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Infrastructure.EF;

#nullable disable

namespace ToDo.Infrastructure.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20230226130234_SeedData4")]
    partial class SeedData4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDo.Core.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToDoListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ToDoItemId");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = new Guid("3da73fe5-a98a-466c-a902-5f6fff1e56c6"),
                            CreatedDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "first item",
                            DueDate = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item1",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("df656403-beb1-4d29-bf39-484d714944d0")
                        },
                        new
                        {
                            ToDoItemId = new Guid("5691f188-650c-4b4f-90d5-6699c10c7c91"),
                            CreatedDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "second item",
                            DueDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item2",
                            Notes = "low priority",
                            Status = 0,
                            ToDoListId = new Guid("df656403-beb1-4d29-bf39-484d714944d0")
                        },
                        new
                        {
                            ToDoItemId = new Guid("7ff94a87-807c-4cc1-9b75-2fd48dfbb8dc"),
                            CreatedDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "first item",
                            DueDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Item1",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("c0d4fa45-4484-446e-b805-940e8697195d")
                        },
                        new
                        {
                            ToDoItemId = new Guid("c1259c08-9c8a-4528-8815-a6b1b4812e0d"),
                            CreatedDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "first item",
                            DueDate = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "First user item",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("7342b3d6-fe52-4961-8d5c-54d7f1d61238")
                        },
                        new
                        {
                            ToDoItemId = new Guid("3532bfda-134d-44ff-81fb-6f1311698d09"),
                            CreatedDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "second item",
                            DueDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Second user item",
                            Notes = "high priority",
                            Status = 0,
                            ToDoListId = new Guid("7342b3d6-fe52-4961-8d5c-54d7f1d61238")
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.Property<Guid>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HiddenFinishedItems")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.HasKey("ToDoListId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ToDoListId = new Guid("df656403-beb1-4d29-bf39-484d714944d0"),
                            HiddenFinishedItems = false,
                            Name = "Admin list1",
                            UserId = new Guid("8eb51707-b6b3-4eaf-9c19-998e00465ba1"),
                            Visibility = true
                        },
                        new
                        {
                            ToDoListId = new Guid("c0d4fa45-4484-446e-b805-940e8697195d"),
                            HiddenFinishedItems = false,
                            Name = "Admin list2",
                            UserId = new Guid("8eb51707-b6b3-4eaf-9c19-998e00465ba1"),
                            Visibility = true
                        },
                        new
                        {
                            ToDoListId = new Guid("7342b3d6-fe52-4961-8d5c-54d7f1d61238"),
                            HiddenFinishedItems = false,
                            Name = "test list1",
                            UserId = new Guid("9d64ab76-09be-40c6-af6c-face028f00da"),
                            Visibility = true
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8eb51707-b6b3-4eaf-9c19-998e00465ba1"),
                            Password = "AQAAAAEAACcQAAAAELb8RYqJdzn7PLBd+LYUfJn41mOC14H7ygPPLYW0R5eQxEoMVo3ztNlSNSaZ+Kcl7w==",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("9d64ab76-09be-40c6-af6c-face028f00da"),
                            Password = "AQAAAAEAACcQAAAAEIPSI/aIdKAHjhvblFJggL1gRyOx5vHTHgGtovz03EPuOfgZ8Tm7o4vWgXk9YWyHKw==",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoItem", b =>
                {
                    b.HasOne("ToDo.Core.Entities.ToDoList", "ToDoList")
                        .WithMany("Items")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.HasOne("ToDo.Core.Entities.User", "User")
                        .WithMany("ToDoLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDo.Core.Entities.ToDoList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ToDo.Core.Entities.User", b =>
                {
                    b.Navigation("ToDoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
